### ISSUE TITLE
Panic failure for amazon/dynamodb-local:1.13.1 image

### ISSUE THREAD

**Issue by ayala-orca** [goodwithtech/dockle#225]
**Description**
When running `dockle amazon/dynamodb-local:1.13.1 --debug`, the run fails with the following error

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/goodwithtech/dockle/pkg/assessor/passwd.PasswdAssessor.Assess({}, 0x19aa5e0?)
	/home/runner/work/dockle/dockle/pkg/assessor/passwd/passwd.go:35 +0x625
github.com/goodwithtech/dockle/pkg/assessor.GetAssessments(0x1d9e6a0?)
	/home/runner/work/dockle/dockle/pkg/assessor/assessor.go:47 +0xcb
github.com/goodwithtech/dockle/pkg/scanner.ScanImage({0x1d9d170, 0xc00011c5a0}, {0x7ff7bfefde2f?, 0x37808e8?}, {0x0?, 0xc00035f728?}, {{0x0, 0x0}, {0x0, 0x0}, ...})
	/home/runner/work/dockle/dockle/pkg/scanner/scan.go:61 +0x505
github.com/goodwithtech/dockle/pkg.Run(0xc000268160)
	/home/runner/work/dockle/dockle/pkg/run.go:87 +0xa28
github.com/urfave/cli.HandleAction({0x196efc0?, 0x1b16818?}, 0xc000234540?)
	/home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x50
github.com/urfave/cli.(*App).Run(0xc000234540, {0xc000190180, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x83c
main.main()
	/home/runner/work/dockle/dockle/cmd/dockle/main.go:12 +0x37
```

**Output of `dockle -v`:**

```
dockle version 0.4.11
```

**Comment by tomoyamachi** [comment]
@ayala-orca 
I'm sorry for late reply.
This issue has been fixed in version 0.4.13.
