### ISSUE TITLE
Runtime error with versions 0.2.4 and 0.2.3

### ISSUE THREAD

**Issue by akshay-1994** [goodwithtech/dockle#68]
**Description**

I wanted to work with container security and chose Dockle for it. But I am unable to make it work. I first tried 0.2.4 version .deb then I got the tar file used the precompiled version and I got the same error:- 

2020-04-15T08:53:45.618Z	DEBUG	There is no .dockleignore file
2020-04-15T08:53:45.618Z	DEBUG	Fetch the latest version from GitHub
2020-04-15T08:53:45.954Z	WARN	A new version v0.2.4 is now available! You have v0.2.3.
2020-04-15T08:53:45.954Z	DEBUG	Start assessments...
fatal error: runtime: out of memory

I tried to run the docker version and got a different error:- 

&{%!w(string=open) %!w(string=<my file>.tar) %!w(syscall.Errno=13)}

I issued the command:-

./dockle --input <image-file.tar> -d 

**What did you expect to happen?**
I expected it to work and show some assessed details.

**What happened instead?**
Out of memory error.

**Output of run with `-debug`:**

```
2020-04-15T08:53:45.618Z	DEBUG	There is no .dockleignore file
2020-04-15T08:53:45.618Z	DEBUG	Fetch latest version from github
2020-04-15T08:53:45.954Z	WARN	A new version v0.2.4 is now available! You have v0.2.3.
2020-04-15T08:53:45.954Z	DEBUG	Start assessments...
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc01fd7, 0x16)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc174000000, 0x100000000, 0x122a3f8)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x12118a0, 0x100000000, 0xc0000e5e00, 0x436057)
	/usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x12118a0, 0x80000, 0xffffffff)
	/usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x12118a0, 0x80000, 0x122a408, 0x11bb8e0)
	/usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x12118a0, 0x80000, 0x101, 0x0)
	/usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x12118a0, 0x80000, 0xc000010101, 0x437145)
	/usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0xfffffe00, 0xc000030101, 0xc000000180)
	/usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0xc00028fa40)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc000138600 sp=0xc0001385f8 pc=0x459200
runtime.mallocgc(0xfffffe00, 0xae7d00, 0x1, 0xc000138718)
	/usr/local/go/src/runtime/malloc.go:1032 +0x895 fp=0xc0001386a0 sp=0xc000138600 pc=0x40c2a5
runtime.makeslice(0xae7d00, 0xfffffe00, 0xfffffe00, 0x40000000)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc0001386d0 sp=0xc0001386a0 pc=0x443cbc
bytes.makeSlice(0xfffffe00, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:229 +0x77 fp=0xc000138738 sp=0xc0001386d0 pc=0x4f65d7
bytes.(*Buffer).grow(0xc000138860, 0x200, 0x40000000)
	/usr/local/go/src/bytes/buffer.go:142 +0x15b fp=0xc000138788 sp=0xc000138738 pc=0x4f5f1b
bytes.(*Buffer).ReadFrom(0xc000138860, 0xd608c0, 0xc0000ae480, 0x0, 0xc000138858, 0x2)
	/usr/local/go/src/bytes/buffer.go:202 +0x4b fp=0xc0001387f8 sp=0xc000138788 pc=0x4f63cb
io/ioutil.readAll(0xd608c0, 0xc0000ae480, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:36 +0x100 fp=0xc000138898 sp=0xc0001387f8 pc=0x4fd050
io/ioutil.ReadAll(...)
	/usr/local/go/src/io/ioutil/ioutil.go:45
github.com/goodwithtech/deckoder/extractor/docker.DockerExtractor.ExtractFromFile(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/goodwithtech/deckoder@v0.0.0-20191103113425-04a81e6f4d7b/extractor/docker/docker.go:307 +0x453 fp=0xc0001390f8 sp=0xc000138898 pc=0xa6ee53
github.com/goodwithtech/deckoder/analyzer.AnalyzeFromFile(0xd71380, 0xc000090010, 0xd69b40, 0xc00000e160, 0xc0003945f0, 0x2, 0xc0003945f0, 0xc0001393c8)
	/go/pkg/mod/github.com/goodwithtech/deckoder@v0.0.0-20191103113425-04a81e6f4d7b/analyzer/analyzer.go:43 +0x225 fp=0xc000139368 sp=0xc0001390f8 pc=0xa71c25
github.com/goodwithtech/dockle/pkg/scanner.ScanImage(0xd71380, 0xc000090010, 0x0, 0x0, 0x7ffd0c26b89b, 0x1e, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/goodwithtech/dockle/pkg/scanner/scan.go:38 +0x1c8 fp=0xc000139480 sp=0xc000139368 pc=0xa72038
github.com/goodwithtech/dockle/pkg.Run(0xc0000bcc60, 0xc0000bcc60, 0xc0001b577f)
	/go/src/github.com/goodwithtech/dockle/pkg/run.go:83 +0x56d fp=0xc000139780 sp=0xc000139480 pc=0xa7305d
github.com/urfave/cli.HandleAction(0xaf9760, 0xc2f2a0, 0xc0000bcc60, 0xc0001eda40, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8 fp=0xc0001397a8 sp=0xc000139780 pc=0x74e078
github.com/urfave/cli.(*App).Run(0xc00032ab60, 0xc00006a080, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c fp=0xc000139ae0 sp=0xc0001397a8 pc=0x74c27c
main.main()
	/go/src/github.com/goodwithtech/dockle/cmd/dockle/main.go:107 +0xa17 fp=0xc000139f60 sp=0xc000139ae0 pc=0xa743b7
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc000139fe0 sp=0xc000139f60 pc=0x42fbde
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000139fe8 sp=0xc000139fe0 pc=0x45b151

goroutine 20 [syscall]:
os/signal.signal_recv(0x45b156)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

**Output of `dockle -v`:**

```
dockle version 0.2.3
```

**Additional details (base image name, container registry info...):**
The image size I am testing is 9.86 GB and the same size worked with Trivy and generated a report for me to analyze. I want to make this tool work as I am fascinated by the CIS benchmarks.

**Comment by akshay-1994** [comment]
Please aid me in solving this. I can provide more information if needed.

**Comment by tomoyamachi** [comment]
@akshay-1994 

Thank you for the report.

> `&{%!w(string=open) %!w(string=.tar) %!w(syscall.Errno=13)}`

Please check #66 if you have the above error.


> fatal error: runtime: out of memory

I will check it. Can you detail the machine's RAM?

**Comment by akshay-1994** [comment]
Hi @tomoyamachi the machine's Ram is 8 gb
